name: fluxivity
description: Experiments in reactivity
version: 1.0.0
homepage: https://github.com/asaph26/fluxivity

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
