name: fluxivity
description: Fluxivity is a package that allows you to build a reactive graph of
  your application's state.
version: 1.6.2
homepage: https://github.com/asaph26/fluxivity

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.12.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.23.1

flutter: null
